### ISSUE TITLE
Ring feedback

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/raw-ipa#62]
Just looking at the code in ring.rs and I'm liking it a fair bit.

There are some things that I think need some consideration though.  Some of this only affects the test implementation.

1. For `Message: Send + Serialize`: I don't see why you would need `Send` (and `'static` for that matter).  If you implement `Serialize`, you can serialize on the same thread as the `send()` call is invoked and then you only need to transfer a buffer of bytes.

2. `Box<[u8]>` == `Vec<u8>`.

3. Buffering.  There is buffering in the `mpsc::channel`.  Why do you need to hold messages in a separate one-item buffer (the `HashMap`)?  Given that the receiver is single-threaded (though it is `Send`), you can just pull from that channel synchronously when calling `receive()`.  The single item buffer already essentially assumes that there is no intermixed messages, so you don't even need to keep the type annotation on each message, just have the serialization fail.

4. Using `Option<Sender>` for peers.  Better to have a setup object instead; see how I did PRSS.  That will allow you to lose the input queue also.

**Comment by akoshelev** [comment]
1. I believe `Message` still needs to be `Send` because we send it across the await point (method `send` on `Ring` trait is `async`). we can get around that by moving serialization to the clients of `send/receive` method but it looks worse to me than the existing implementation.

2. Is there a particular reason why you would prefer `Vec` over `Box`? The latter is not a growable container and takes only 66% of the space on the stack compared to `Vec`. None of these matter for the test implementation, I did it mostly just to educate folks less familiar with Rust that it is also possible to have an exclusive pointer to slice that does not support adding/removing elements from it.

3. I was afraid that FIFO without buffering may not cover all of our use cases. For multiplication it certainly works out of the box, would it be enough to cover cases where H1 and H3 need to send two different messages to H2 that can process them in any order? I am not convinced that we would need that ever, so I don't mind changing it but would be great if you can confirm that this is entirely redundant in this case

4. Makes sense, I would probably use `Builder` pattern as the most common and because pretty much everyone is familiar with it

**Comment by akoshelev** [comment]
@martinthomson does this sound reasonable?

**Comment by martinthomson** [comment]
Not sure about 1.  If the `send()` call turns the message into bytes immediately, then it never has to cross between threads, only the bytes do.

Good point about `Box<[u8]>`, though that is a level of optimization that rarely matters: stack space is hardly scarce and the effect of going from 3 to 1 pointer/usize variable is something I'd generally wait for profiles on before trying to tweak.

On 3, I think that the way to deal with this is to create multiple flows between peers.  You can do this with protocol-level multiplexing, or - in the case of mpsc - a channel that allows you to create labeled channels.  One-per-transaction actions like that are probably fine.

**Comment by akoshelev** [comment]
1. it is a little unclear to me how it would work if `send` method is async. If we call `send(message).await` doesn't it mean that executor may schedule this task in a different thread? for `receive` I believe it is the same - we deserialize bytes to typed message in one thread, but then we have to send it across the await point which makes it `Send` imo. 

3. Good point about using built-in channel buffers. I'll probably just change that to use a single channel per peer with hope that we won't require concurrent flows any time soon.  I'll sync up with you offline on how we can implement it in the future

**Comment by martinthomson** [comment]
Another point to add here: "Ring" is going to be a bad name.  If we do end up implementing using a $\mathbb{Z}_{2^n}$ ring rather than a prime field (which would be much faster), we'll want a type for that.  Maybe we can use "Mesh" or "Comms" or something like that instead.

**Comment by akoshelev** [comment]
#82 addresses most of these, except 3 (buffering)
